Get http://localhost:8000/users


###
POST http://localhost:8000/login
Content-Type: application/json

{
    "name": "Bruno",
    "password": "password"
}

###
POST http://localhost:0000/users/login
Content-Type: application/json

{
    "name": "Bruno",
    "password": "pass"
}